services:
  user-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    volumes:
      - tmp-new-dev:/var/lib/postgresql/data
      - './order-service/config/create-order-database.sql:/docker-entrypoint-initdb.d/create-order-database.sql'
      - './product-service/config/create-product-database.sql:/docker-entrypoint-initdb.d/create-product-database.sql'
      
    ports:
      - "5432:5432"

volumes:
  tmp-new-dev:
